/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/professionals`; params?: Router.UnknownInputParams; } | { pathname: `/professionals/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/setup`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/professionals/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownOutputParams; } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/professionals`; params?: Router.UnknownOutputParams; } | { pathname: `/professionals/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/setup`; params?: Router.UnknownOutputParams; } | { pathname: `/services`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/professionals/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/callback${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `/professionals${`?${string}` | `#${string}` | ''}` | `/professionals/profile/edit${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/profile/setup${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/professionals`; params?: Router.UnknownInputParams; } | { pathname: `/professionals/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/setup`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | `/professionals/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/professionals/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
